project:
  type: website
  output-dir: docs
  resources: 
    - "CNAME"

website:
  title: "Helen Schmidt"
  favicon: images/logo-light.png
  navbar:
    pinned: true
    right:
      - href: index.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: portfolio.qmd
        text: Portfolio
      - href: resources.qmd
        text: Resources
      - href: files/Schmidt-CV.pdf
        text: CV

format:
  html:
    theme: flatly
    toc: false
    grid:
      sidebar-width: 150px
      margin-width: 200px
    

editor: source


