---
title: "About Me"
format: 
  html:
    page-layout: full
---

Hello! My name is Helen Schmidt and I am a Social Psychology & Quantitative Methods PhD student in the [Social and Affective Neuroscience Lab](https://sites.temple.edu/sanlab/){target="_blank"} at Temple University. Under the guidance of Dr. Chelsea Helion, my research focuses on the relationship between emotion and language in social contexts. I am passionate about employing a multimodal approach to my research, combining traditional behavioral and neuroimaging tools with machine learning and advanced quantitative methods.

Previously, I worked as the lab coordinator in Dr. Maureen Ritchey's [Memory Modulation Lab](http://www.thememolab.org/){target="_blank"} at Boston College, where I studied how retrieval strategies impacted memory for emotional information. Before that, I completed my undergraduate studies at Tufts University, where I graduated with a BS in biology in 2017. During my time at Tufts, I worked with Dr. Elizabeth Race in the [Integrative Cognitive Neuroscience Lab](https://tuftsiconlab.weebly.com/){target="_blank"} to investigate how attention and mind-wandering impacted memory quality. I also completed a MSc in clinical neuroscience at University College London, where I studied learning and decision-making in affective contexts.

Outside of the lab, I can be found reading books, exploring new places, drinking coffee, and spending time outside. I'm also a huge `ggplot` enthusiast - you can find some of my R projects in my [portfolio](portfolio.qmd).
